# ==========================================
# EXPERIMENT IDENTIFICATION
# ==========================================
seed: 42                           
output_dir: "./output"

# ==========================================
# GLOBAL PHYSICS CONSTANTS
# ==========================================
physics: &phys_constants
  equation: viscoelastic_residual_Fung
  "relaxation_modulus" : 15.0
  "stress_scaling_factor": 0.88
  "exponential_non_linearity": 13.0
  "stress": 10.0

# ==========================================
# MODEL CONFIGURATION
# ==========================================
model:
  model_name: "1d_pinn_viscoelastic"
  architecture: "MLP"
  in_channels: 1
  hidden_layers: 3
  hidden_dim: 32
  out_class: 2

# ==========================================
# DATA & DATA LOADING
# ==========================================
data:
  dataset_name: "time_points.pt"
  data_dir: "./data/synt"
  batch_size: 64
  num_workers: 4                   

synt:
  domain: [0.0, 10.0, 5000]
  parameters:
    todo: 0.0
  data_dir: "./data/synt"

# ==========================================
# TRAINING CONFIGURATION
# ==========================================
training:
  device: "cpu"
  epochs: 5000
  parameters:
    <<: *phys_constants
    intial_strain: 0
  loss_weights:
    lambda_ic: 1e3
    lambda_bc: 1e3
    lambda_r: 1e1

# ==========================================
# TESTING 
# ==========================================
testing:
  device: "cpu" 
  todo: 0.0

# ==========================================
# OPTIMIZER
# ==========================================
optimizer:
  name: "adam"                    
  lr: 0.001                        
  weight_decay: 0.0