import numpy as np
from dataclasses import dataclass


@dataclass
class GraphFeatures:
    """
    Geometric and mechanical features associated
    with the nodes and edges of the graph.

    Node features:
        [X, Y, x, y, ux, uy]

    Edge features:
        [dX, dY, L0, dx, dy, L]

    where:

        X  = reference position
        x  = current position
        u  = displacement
        dX = reference relative position
        L0 = reference edge length
        dx = current relative position
        L  = current edge length
    """

    node_features: np.ndarray
    edge_features: np.ndarray

    @property
    def n_nodes(self):
        return self.node_features.shape[0]

    @property
    def n_node_features(self):
        return self.node_features.shape[1]

    @property
    def n_edges(self):
        return self.edge_features.shape[0]

    @property
    def n_edge_features(self):
        return self.edge_features.shape[1]


def create_features(
    graph,
    reference_nodes=None,
    current_nodes=None
):
    """
    Create geometric and mechanical features for the graph.

    Parameters
    ----------
    graph : Graph
        Graph generated by graph.py.

    reference_nodes : ndarray, shape (N, 2), optional
        Node coordinates in the reference configuration X.

        If omitted, graph.nodes are used as the reference
        configuration.

    current_nodes : ndarray, shape (N, 2), optional
        Node coordinates in the current/deformed configuration x.

        If omitted, graph.nodes are used.

    Returns
    -------
    GraphFeatures
        Node and edge features.

    Notes
    -----
    For the current 2D implementation:

        u = x - X

    Node features are:

        [X, Y, x, y, ux, uy]

    Edge features are:

        [dX, dY, L0, dx, dy, L]
    """

    # =========================================================
    # INPUT
    # =========================================================

    graph_nodes = np.asarray(
        graph.nodes,
        dtype=float
    )

    if graph_nodes.ndim != 2 or graph_nodes.shape[1] != 2:
        raise ValueError(
            "graph.nodes must have shape (N, 2)."
        )

    N = graph_nodes.shape[0]

    # ---------------------------------------------------------
    # Reference configuration
    # ---------------------------------------------------------

    if reference_nodes is None:
        reference_nodes = graph_nodes.copy()
    else:
        reference_nodes = np.asarray(
            reference_nodes,
            dtype=float
        )

    if reference_nodes.shape != (N, 2):
        raise ValueError(
            "reference_nodes must have shape (N, 2)."
        )

    # ---------------------------------------------------------
    # Current configuration
    # ---------------------------------------------------------

    if current_nodes is None:
        current_nodes = graph_nodes.copy()
    else:
        current_nodes = np.asarray(
            current_nodes,
            dtype=float
        )

    if current_nodes.shape != (N, 2):
        raise ValueError(
            "current_nodes must have shape (N, 2)."
        )

    # =========================================================
    # NODE FEATURES
    # =========================================================

    # Displacement field:
    #
    #     u = x - X
    #
    displacement = (
        current_nodes
        -
        reference_nodes
    )

    # Node feature vector:
    #
    # [X, Y, x, y, ux, uy]
    #
    node_features = np.concatenate(
        [
            reference_nodes,
            current_nodes,
            displacement
        ],
        axis=1
    )

    # =========================================================
    # EDGE FEATURES
    # =========================================================

    senders = np.asarray(
        graph.senders,
        dtype=int
    )

    receivers = np.asarray(
        graph.receivers,
        dtype=int
    )

    if senders.shape != receivers.shape:
        raise ValueError(
            "graph.senders and graph.receivers "
            "must have the same shape."
        )

    # ---------------------------------------------------------
    # Reference edge geometry
    # ---------------------------------------------------------

    reference_sender_positions = (
        reference_nodes[senders]
    )

    reference_receiver_positions = (
        reference_nodes[receivers]
    )

    reference_relative_position = (
        reference_receiver_positions
        -
        reference_sender_positions
    )

    reference_distance = np.linalg.norm(
        reference_relative_position,
        axis=1,
        keepdims=True
    )

    # ---------------------------------------------------------
    # Current edge geometry
    # ---------------------------------------------------------

    current_sender_positions = (
        current_nodes[senders]
    )

    current_receiver_positions = (
        current_nodes[receivers]
    )

    current_relative_position = (
        current_receiver_positions
        -
        current_sender_positions
    )

    current_distance = np.linalg.norm(
        current_relative_position,
        axis=1,
        keepdims=True
    )

    # ---------------------------------------------------------
    # Edge feature vector
    #
    # [dX, dY, L0, dx, dy, L]
    # ---------------------------------------------------------

    edge_features = np.concatenate(
        [
            reference_relative_position,
            reference_distance,
            current_relative_position,
            current_distance
        ],
        axis=1
    )

    return GraphFeatures(
        node_features=node_features,
        edge_features=edge_features
    )


# =============================================================
# TEST
# =============================================================

if __name__ == "__main__":

    from src.mesh.mesh import create_mesh
    from src.graph.graph import create_graph

    print("=" * 70)
    print("GRAPH FEATURES MODULE TEST")
    print("=" * 70)

    # ---------------------------------------------------------
    # Create reference mesh
    # ---------------------------------------------------------

    mesh = create_mesh(
        width=1.0,
        height=1.0,
        nx=5,
        ny=5
    )

    # ---------------------------------------------------------
    # Create graph
    # ---------------------------------------------------------

    graph = create_graph(mesh)

    # ---------------------------------------------------------
    # Reference configuration
    # ---------------------------------------------------------

    X = graph.nodes.copy()

    # ---------------------------------------------------------
    # Create a simple deformation
    #
    # x = F X
    #
    # F =
    #
    # [1.1  0.1]
    # [0.0  0.9]
    #
    # ---------------------------------------------------------

    F = np.array([
        [1.1, 0.1],
        [0.0, 0.9]
    ])

    x = (F @ X.T).T

    # ---------------------------------------------------------
    # Create features
    # ---------------------------------------------------------

    features = create_features(
        graph,
        reference_nodes=X,
        current_nodes=x
    )

    # =========================================================
    # OUTPUT
    # =========================================================

    print("\nNumber of nodes:")
    print(features.n_nodes)

    print("\nNode feature dimension:")
    print(features.n_node_features)

    print("\nNumber of edges:")
    print(features.n_edges)

    print("\nEdge feature dimension:")
    print(features.n_edge_features)

    print("\nFirst node features:")
    print(features.node_features[:5])

    print("\nFirst edge features:")
    print(features.edge_features[:5])

    # =========================================================
    # CHECKS
    # =========================================================

    expected_node_dimension = 6
    expected_edge_dimension = 6

    node_dimension_ok = (
        features.n_node_features
        ==
        expected_node_dimension
    )

    edge_dimension_ok = (
        features.n_edge_features
        ==
        expected_edge_dimension
    )

    # ---------------------------------------------------------
    # Check displacement
    # ---------------------------------------------------------

    expected_displacement = x - X

    computed_displacement = (
        features.node_features[:, 4:6]
    )

    displacement_error = np.max(
        np.abs(
            computed_displacement
            -
            expected_displacement
        )
    )

    # ---------------------------------------------------------
    # Check reference edge length
    # ---------------------------------------------------------

    first_sender = graph.senders[0]
    first_receiver = graph.receivers[0]

    expected_dX = (
        X[first_receiver]
        -
        X[first_sender]
    )

    expected_L0 = np.linalg.norm(
        expected_dX
    )

    first_edge = features.edge_features[0]

    edge_reference_error = np.max(
        np.abs(
            first_edge[:2]
            -
            expected_dX
        )
    )

    edge_length_error = abs(
        first_edge[2]
        -
        expected_L0
    )

    # =========================================================
    # RESULTS
    # =========================================================

    print("\n" + "-" * 70)
    print("CHECKS")
    print("-" * 70)

    print(
        "\nNode feature dimension:",
        "PASS" if node_dimension_ok else "FAIL"
    )

    print(
        "Edge feature dimension:",
        "PASS" if edge_dimension_ok else "FAIL"
    )

    print(
        "Displacement computation:",
        "PASS" if displacement_error < 1e-12
        else "FAIL"
    )

    print(
        "Reference edge vector:",
        "PASS" if edge_reference_error < 1e-12
        else "FAIL"
    )

    print(
        "Reference edge length:",
        "PASS" if edge_length_error < 1e-12
        else "FAIL"
    )

    # ---------------------------------------------------------
    # Final result
    # ---------------------------------------------------------

    all_passed = (
        node_dimension_ok
        and edge_dimension_ok
        and displacement_error < 1e-12
        and edge_reference_error < 1e-12
        and edge_length_error < 1e-12
    )

    print("\n" + "=" * 70)

    if all_passed:
        print("RESULT: PASS")
    else:
        print("RESULT: FAIL")