import numpy as np
from dataclasses import dataclass


@dataclass
class GraphFeatures:
    """
    Features associated with the nodes and edges of the graph.

    node_features:
        Shape (N, F_node)

    edge_features:
        Shape (E, F_edge)
    """

    node_features: np.ndarray
    edge_features: np.ndarray

    @property
    def n_nodes(self):
        return self.node_features.shape[0]

    @property
    def n_node_features(self):
        return self.node_features.shape[1]

    @property
    def n_edges(self):
        return self.edge_features.shape[0]

    @property
    def n_edge_features(self):
        return self.edge_features.shape[1]


def create_features(graph):
    """
    Create initial geometric features for the graph.

    Parameters
    ----------
    graph : Graph
        Graph generated by graph.py.

    Returns
    -------
    GraphFeatures
        Node and edge features.
    """

    # =========================================================
    # NODE FEATURES
    # =========================================================

    # For now each node is represented by its coordinates.
    node_features = graph.nodes.copy()


    # =========================================================
    # EDGE FEATURES
    # =========================================================

    senders = graph.senders
    receivers = graph.receivers

    sender_positions = graph.nodes[senders]
    receiver_positions = graph.nodes[receivers]

    # Relative displacement between the two nodes
    relative_position = receiver_positions - sender_positions

    # Euclidean distance
    distance = np.linalg.norm(
        relative_position,
        axis=1,
        keepdims=True
    )

    # Concatenate:
    #
    # [dx, dy, distance]
    #
    edge_features = np.concatenate(
        [
            relative_position,
            distance
        ],
        axis=1
    )

    return GraphFeatures(
        node_features=node_features,
        edge_features=edge_features
    )


# =============================================================
# TEST
# =============================================================

if __name__ == "__main__":

    from src.mesh.mesh import create_mesh
    from src.graph.graph import create_graph

    # Create mesh
    mesh = create_mesh(
        width=1.0,
        height=1.0,
        nx=5,
        ny=5
    )

    # Create graph
    graph = create_graph(mesh)

    # Create features
    features = create_features(graph)

    print("===== GRAPH FEATURES =====")

    print(f"Number of nodes: {features.n_nodes}")
    print(
        f"Node feature dimension: "
        f"{features.n_node_features}"
    )

    print(f"Number of edges: {features.n_edges}")
    print(
        f"Edge feature dimension: "
        f"{features.n_edge_features}"
    )

    print("\nFirst node features:")
    print(features.node_features[:5])

    print("\nFirst edge features:")
    print(features.edge_features[:5])