import numpy as np
import matplotlib.pyplot as plt
from dataclasses import dataclass


@dataclass
class Graph:
    """
    Graph representation of a mesh.

    The graph is defined as:

        G = (V, E)

    where:

        V = mesh nodes
        E = directed mesh edges

    Attributes
    ----------
    nodes : np.ndarray
        Node coordinates.
        Shape: (N, 2)

    mesh_edges : np.ndarray
        Original undirected mesh edges.
        Shape: (E, 2)

    senders : np.ndarray
        Sender node for each directed edge.
        Shape: (2E,)

    receivers : np.ndarray
        Receiver node for each directed edge.
        Shape: (2E,)
    """

    nodes: np.ndarray
    mesh_edges: np.ndarray
    senders: np.ndarray
    receivers: np.ndarray

    @property
    def n_nodes(self):
        return len(self.nodes)

    @property
    def n_mesh_edges(self):
        return len(self.mesh_edges)

    @property
    def n_directed_edges(self):
        return len(self.senders)


def create_graph(mesh):
    """
    Create a graph from an existing Mesh object.

    Parameters
    ----------
    mesh : Mesh
        Mesh generated by mesh.py.

    Returns
    -------
    Graph
        Graph representation of the mesh.
    """

    # ---------------------------------------------------------
    # 1. Nodes
    # ---------------------------------------------------------

    nodes = mesh.nodes.copy()

    # ---------------------------------------------------------
    # 2. Mesh edges
    # ---------------------------------------------------------

    mesh_edges = mesh.edges.copy()

    # ---------------------------------------------------------
    # 3. Create directed edges
    # ---------------------------------------------------------

    senders = []
    receivers = []

    for edge in mesh_edges:

        node_a, node_b = edge

        # A → B
        senders.append(node_a)
        receivers.append(node_b)

        # B → A
        senders.append(node_b)
        receivers.append(node_a)

    senders = np.array(senders, dtype=int)
    receivers = np.array(receivers, dtype=int)

    # ---------------------------------------------------------
    # 4. Create Graph object
    # ---------------------------------------------------------

    return Graph(
        nodes=nodes,
        mesh_edges=mesh_edges,
        senders=senders,
        receivers=receivers
    )


def plot_graph(graph):
    """
    Visualize the graph structure.
    """

    fig, ax = plt.subplots(figsize=(7, 7))

    # ---------------------------------------------------------
    # Draw edges
    # ---------------------------------------------------------

    for sender, receiver in zip(
        graph.senders,
        graph.receivers
    ):

        start = graph.nodes[sender]
        end = graph.nodes[receiver]

        ax.plot(
            [start[0], end[0]],
            [start[1], end[1]],
            linewidth=0.8
        )

    # ---------------------------------------------------------
    # Draw nodes
    # ---------------------------------------------------------

    ax.scatter(
        graph.nodes[:, 0],
        graph.nodes[:, 1],
        s=30
    )

    # ---------------------------------------------------------
    # Node labels
    # ---------------------------------------------------------

    for i, (x, y) in enumerate(graph.nodes):

        ax.text(
            x,
            y,
            str(i),
            fontsize=8
        )

    ax.set_aspect("equal")

    ax.set_xlabel("x")
    ax.set_ylabel("y")

    ax.set_title(
        f"Mesh Graph | "
        f"Nodes: {graph.n_nodes} | "
        f"Mesh edges: {graph.n_mesh_edges} | "
        f"Directed edges: {graph.n_directed_edges}"
    )

    ax.grid(True)

    plt.show()


# =============================================================
# TEST
# =============================================================
if __name__ == "__main__":

    from src.mesh.mesh import create_mesh

    mesh = create_mesh(
        width=1.0,
        height=1.0,
        nx=5,
        ny=5
    )

    graph = create_graph(mesh)

    print("===== GRAPH INFORMATION =====")

    print(f"Number of nodes: {graph.n_nodes}")
    print(f"Number of mesh edges: {graph.n_mesh_edges}")
    print(f"Number of directed edges: {graph.n_directed_edges}")

    print("\nFirst mesh edges:")
    print(graph.mesh_edges[:10])

    print("\nFirst senders:")
    print(graph.senders[:10])

    print("\nFirst receivers:")
    print(graph.receivers[:10])

    plot_graph(graph)