from dataclasses import dataclass

import matplotlib.pyplot as plt
import torch
from src.mesh import create_mesh


@dataclass
class Graph:
    """
    Graph representation of a mesh.

    The graph is defined as:

        G = (V, E)

    where:

        V = mesh nodes
        E = directed mesh edges

    Attributes
    ----------
    nodes : np.ndarray
        Node coordinates.
        Shape: (N, 2)

    mesh_edges : np.ndarray
        Original undirected mesh edges.
        Shape: (E, 2)

    senders : np.ndarray
        Sender node for each directed edge.
        Shape: (2E,)

    receivers : np.ndarray
        Receiver node for each directed edge.
        Shape: (2E,)
    """

    nodes: torch.Tensor
    mesh_edges: torch.Tensor
    senders: torch.Tensor
    receivers: torch.Tensor

    @property
    def n_nodes(self):
        return len(self.nodes)

    @property
    def n_mesh_edges(self):
        return len(self.mesh_edges)

    @property
    def n_directed_edges(self):
        return len(self.senders)


def create_graph(mesh):
    """
    Create a graph from an existing Mesh object.

    Parameters
    ----------
    mesh : Mesh
        Mesh generated by mesh.py.

    Returns
    -------
    Graph
        Graph representation of the mesh.
    """

    # ---------------------------------------------------------
    # 1. Nodes
    # ---------------------------------------------------------

    nodes = mesh.nodes.copy()

    # ---------------------------------------------------------
    # 2. Mesh edges
    # ---------------------------------------------------------

    mesh_edges = mesh.edges.copy()

    # ---------------------------------------------------------
    # 3. Create directed edges
    # ---------------------------------------------------------

    senders = []
    receivers = []

    for edge in mesh_edges:

        node_a, node_b = edge

        # A → B
        senders.append(node_a)
        receivers.append(node_b)

        # B → A
        senders.append(node_b)
        receivers.append(node_a)

    senders = torch.tensor(senders, dtype=torch.long)
    receivers = torch.tensor(receivers, dtype=torch.long)

    # ---------------------------------------------------------
    # 4. Create Graph object
    # ---------------------------------------------------------

    return Graph(
        nodes=nodes,
        mesh_edges=mesh_edges,
        senders=senders,
        receivers=receivers
    )