from dataclasses import dataclass

import matplotlib.pyplot as plt
import numpy as np

from .mesh import create_mesh


@dataclass
class Grid:
    """
    Represents the spatial points used by the PINN.

    In the first version of the project, the PINN points
    coincide with the mesh nodes.

    Attributes
    ----------
    points : np.ndarray
        Spatial coordinates of the PINN points.
        Shape: (N, 2)

    boundary_points : np.ndarray
        Indices of points belonging to the boundary.

    interior_points : np.ndarray
        Indices of points inside the domain.
    """

    points: np.ndarray
    boundary_points: np.ndarray
    interior_points: np.ndarray

    @property
    def n_points(self):
        """Total number of PINN points."""
        return len(self.points)

    @property
    def n_boundary(self):
        """Number of boundary points."""
        return len(self.boundary_points)

    @property
    def n_interior(self):
        """Number of interior points."""
        return len(self.interior_points)


def create_grid(mesh):
    """
    Create the PINN grid from an existing mesh.

    The PINN collocation points are exactly the mesh nodes.

    Parameters
    ----------
    mesh : Mesh
        Mesh object generated by mesh.py.

    Returns
    -------
    Grid
        Grid containing the mesh nodes as PINN points.
    """

    # ---------------------------------------------------------
    # 1. Use mesh nodes as PINN points
    # ---------------------------------------------------------

    points = mesh.nodes.copy()

    # ---------------------------------------------------------
    # 2. Boundary points
    # ---------------------------------------------------------

    boundary_points = mesh.boundary_nodes.copy()

    # ---------------------------------------------------------
    # 3. Interior points
    # ---------------------------------------------------------

    all_indices = np.arange(len(points))

    interior_mask = np.ones(len(points), dtype=bool)

    interior_mask[boundary_points] = False

    interior_points = all_indices[interior_mask]

    # ---------------------------------------------------------
    # 4. Return Grid object
    # ---------------------------------------------------------

    return Grid(
        points=points,
        boundary_points=boundary_points,
        interior_points=interior_points
    )


def plot_grid(grid):
    """
    Plot the PINN points.
    """

    _fig, ax = plt.subplots(figsize=(7, 7))

    # Interior points
    interior = grid.points[grid.interior_points]

    ax.scatter(
        interior[:, 0],
        interior[:, 1],
        s=30,
        label="Interior points"
    )

    # Boundary points
    boundary = grid.points[grid.boundary_points]

    ax.scatter(
        boundary[:, 0],
        boundary[:, 1],
        s=50,
        label="Boundary points"
    )

    ax.set_aspect("equal")

    ax.set_xlabel("x")
    ax.set_ylabel("y")

    ax.set_title(
        f"PINN Grid | "
        f"Points: {grid.n_points} | "
        f"Interior: {grid.n_interior} | "
        f"Boundary: {grid.n_boundary}"
    )

    ax.legend()
    ax.grid(True)

    plt.show()


# =============================================================
# TEST
# =============================================================

if __name__ == "__main__":

    # Create the mesh
    mesh = create_mesh(
        width=1.0,
        height=1.0,
        nx=5,
        ny=5
    )

    # Create the PINN grid from the mesh
    grid = create_grid(mesh)

    print("===== GRID INFORMATION =====")

    print(f"Total points: {grid.n_points}")
    print(f"Interior points: {grid.n_interior}")
    print(f"Boundary points: {grid.n_boundary}")

    print("\nFirst points:")
    print(grid.points[:5])

    print("\nBoundary point indices:")
    print(grid.boundary_points)

    print("\nInterior point indices:")
    print(grid.interior_points)

    plot_grid(grid)